#! usr/bin/perl
use warnings;
use feature qw(say switch);


%keywordsWithResponses = (

              "CAN YOU" => ["Don't you believe that I can<*", "Perhaps you would like to be able to<*", "You want me to be able to<*"],
              "CAN I", => ["Perhaps you don't want to<*", "Do you want to be able to<*"],
              "YOU ARE" => ["What makes you think I am<*", "Does it please you to believe I am<*", "Perhaps you would like to be<*", "Do you sometimes wish you were<*"],
              "YOU'RE" => ["What makes you think I am<*", "Does it please you to believe I am<*", "Perhaps you would like to be<*", "Do you sometimes wish you were<*"],
              "I DON'T" => [],
              "I FEEL" => [],
              "WHY DON'T YOU" => [],
              "WHY CAN'T I" => [],
              "ARE YOU" => [],
              "I CAN'T" => [],
              "I AM" => [],
              "I'M" => [],
              "YOU" => [],
              "I WANT" => [],
              "WHAT" => [],
              "HOW" => [],
              "WHO" => [],
              "WHERE" => [],
              "WHEN" => [],
              "WHY" => [],
              "NAME" => [],
              "CAUSE" => [],
              "SORRY" => [],
              "DREAM" => [],
              "HELLO" => [],
              "HI" => [],
              "MAYBE" => [],
              "NO" => [],
              "YOUR" => [],
              "ALWAYS" => [],
              "THINK" => [],
              "ALIKE" => [],
              "YES" => [],
              "FRIEND" => [],
              "COMPUTER" => [],
              "NO KEY FOUND" => [],
              "REPEAT INPUT" => [],
            );

@responses = (       
               
               "Don't you really<*",
               "Why don't you<*",
               "Do you wish to be able to<*",
               "Does that trouble you?",
               "Tell me more about such feelings.",
               "Do you often feel<*",
               "Do you enjoy feeling<*",
               "Do you really believe I don't<*",
               "Perhaps in good time I will<@",
               "Do you want me to<*",
               "Do you think you should be able to<*",
               "Why can't you<*",
               "Why are you interested in whether or not I am<*",
               "Would you prefer if I were not<*",
               "Perhaps in your fantasies I am<*",
               "How do you know you can't<*",
               "Have you tried?",
               "Perhaps you can now<*",
               "Did you come to me because you are<*",
               "How long have you been<*".
               "Do you believe it is normal to be<*",
               "Do you enjoy being<*",
               "We were discussing you, not me.",
               "Oh... <*",
               "You're not really talking about me, are you?",
               "What would it mean to you if you got<*",
               "Why do you want<*",
               "Suppose you got<*",
               "What if you never got<*",
               "I sometimes also want<@",
               "Why do you ask?",
               "Does that question interest you?",
               "What answer would please you the most?",
               "What do you think?",
               "Are such questions on your mind often?",
               "What is it that you really want to know?",
               "Have you asked anyone else?",
               "Have you asked such questions before?",
               "What else comes to mind when you ask that?",
               "Names don't interest me.",
               "I don't care about names, please go on.",
               "Is that the real reason?",
               "Don't any other reasons come to mind?",
               "Does that reason explain anything else?",
               "What other reasons might there be?",
               "Please don't apologise!",
               "Apologies are not necessary.",
               "What feelings do you have when you apologise?",
               "Don't be so defensive!",
               "What does that dream suggest to you?",
               "Do you dream often?",
               "What persons appear in your dreams?",
               "Are you disturbed by your dreams?",
               "How are you today.. What would you like to discuss?",
               "You don't seem quite certain.",
               "Why the uncertain tone?",
               "Can't you be more positive?",
               "You aren't sure?",
               "Don't you know?",
               "Are you saying no just to be negative?",
               "You are being a bit negative.",
               "Why not?",
               "Are you sure?",
               "Why no?",
               "Why are you concerned about my<*",
               "What about your own<*",
               "Can you think of a specific example?",
               "When?",
               "What are you thinking of?",
               "Really, always?",
               "Do you really think so?",
               "But you are not sure you<*",
               "Do you doubt you<*",
               "In what way?",
               "What resemblence do you see?",
               "What does the similarity suggest to you?",
               "What other connections do you see?",
               "Could there really be some connection?",
               "How?",
               "You seem quite positive.",
               "Are you Sure?",
               "I see.",
               "I understand.",
               "Why do you bring up the topic of friends?",
               "Do your friends worry you?",
               "Do your friends pick on you?",
               "Are you sure you have any friends?",
               "Do you impose on your friends?",
               "Perhaps your love for friends worries you.",
               "Do computers worry you?",
               "Are you talking about me in particular?",
               "Are you frightened by machines?",
               "Why do you mention computers?",
               "What do you think machines have to do with your problems?",
               "Don't you think computers can help people?",
               "What is it about machines that worries you?",
               "Say, do you have any psychological problems?",
               "What does that suggest to you?",
               "I see.",
               "I'm not sure I understand you fully.",
               "Come, come, elucidate your thoughts.",
               "Can you elaborate on that?",
               "That is quite interesting.",
               "Why did you repeat yourself?",
               "Do you expect a different answer by repeating yourself?",
               "Come, come, elucidate your thoughts.",
               "Please don't repeat yourself!",
              );


@postConj = (
  		        "am",
   		        "are",
 		          "was",
    		      "were",
   			      "you",
    		      "you",
   		        "me",
   		        "your",
  		        "my",
  		        "your's",
 	            "mine",
  		        "you're",
 	            "I'm",
 		          "you've",
 	            "I've",
		          "you'll",
 	            "I'll",
 	            "yourself",
	            "myself",
            );

my %preToPost = (
    "me am"  => "I am",
    "am me" => "am I",
    "me can"  => "I can",
    "can me" => "can I",
    "me have" => "I have",
    "me will" => "I will",
    "will me" => "will I"
);

@preConj = (
              "are",
              "am",
              "were",
              "was",
              "I",
              "me",
              "you",
              "my",
              "your",
              "mine",
              "your's",
              "I'm",
              "you're",
              "I've",
              "you've",
              "I'll",
              "you'll",
              "myself",
              "yourself",
            );

$keySize = @keywords;
$noKey = @keywords - 1;
$responsesSize = responses;


print "Hello I am Eliza. What problems are you having today?\n";

while(<STDIN>){
  last if ($_ =~ /^\s*$/); # Exit if it was just spaces (or just an enter)
  $string = $_;
  $string = stripString($string);
  $string = conjugate($string);
  $string = correctTense($string); 
  say $string."?";
}

sub stripString {
  $string = $_[0];
  $string =~ tr/a-zA-z //dc;

  return $string;
}

sub conjugate {
  $string = $_[0];
  @stringWords = split (" ",$string);
  foreach my $word (@stringWords) {
    for ($i = 0;$i< @preConj;$i++) {
      if ($word eq $preConj[$i]) {
          $word = $postConj[$i];
          last;
      }
    }   
  }
  return join (" ", @stringWords);
}

sub correctTense {
  $string = $_[0];
  for my $phrase (keys %preToPost) {
    $string =~ s/$phrase/$preToPost{$phrase}/g;
  }
    return $string;
    #print "The right tense of '$phrase' is $preToPost{$phrase}\n";

}

