#! usr/bin/perl
use warnings;
use feature qw(say switch);


%keywordsWithResponses = (
              "CAN YOU" => ["Don't you believe that I can <Q>", "Perhaps you would like to be able to<*", "You want me to be able to <Q>"],
              "CAN I", => ["Perhaps you don't want to <Q>", "Do you want to be able to <Q>"],
              "YOU ARE" => ["What makes you think I am <Q>", "Does it please you to believe I am <Q>", "Perhaps you would like to be <Q>", "Do you sometimes wish you were <Q>"],
              "YOU'RE" => ["What makes you think I am <Q>", "Does it please you to believe I am <Q>", "Perhaps you would like to be <Q>", "Do you sometimes wish you were <Q>"],
              "I DON'T" => ["Don't you really <Q>","Why don't you <Q>","Do you wish to be able to <Q>","Does that trouble you?"],
              "I FEEL" => ["Tell me more about such feelings.","Do you often feel <Q>","Do you enjoy feeling <Q>"],
              "WHY DON'T YOU" => ["Do you really believe I don't <Q>", "Perhaps in good time I will <S>","Do you want me to <Q>"],
              "WHY CAN'T I" => ["Do you think you should be able to <Q>","Why can't you <Q>"],
              "ARE YOU" => ["Why are you interested in whether or not I am <Q>","Would you prefer if I were not <Q>","Perhaps in your fantasies I am <Q>"],
              "I CAN'T" => ["How do you know you can't <Q>","Have you tried?","Perhaps you can now <Q>"],
              "I AM" => ["Did you come to me because you are <Q>","How long have you been <Q>","Do you believe it is normal to be <Q>","Do you enjoy being <Q>"],
              "I'M" => ["Did you come to me because you are <Q>","How long have you been <Q>","Do you believe it is normal to be <Q>","Do you enjoy being <Q>"],
              "YOU" => ["We were discussing you, not me.","Oh... <Q>","You're not really talking about me, are you?"],
              "I WANT" => ["What would it mean to you if you got <Q>", "Why do you want <Q>","Suppose you got <Q>","What if you never got <Q>","I sometimes also want <S>"],
              "WHAT" => ["Why do you ask?","Does that question interest you?","What answer would please you the most?","What do you think?","Are such questions on your mind often?","What is it that you really want to know?","Have you asked anyone else?","Have you asked such questions before?","What else comes to mind when you ask that?"],
              "HOW" => ["Why do you ask?","Does that question interest you?","What answer would please you the most?","What do you think?","Are such questions on your mind often?","What is it that you really want to know?","Have you asked anyone else?","Have you asked such questions before?","What else comes to mind when you ask that?"],
              "WHO" => ["Why do you ask?","Does that question interest you?","What answer would please you the most?","What do you think?","Are such questions on your mind often?","What is it that you really want to know?","Have you asked anyone else?","Have you asked such questions before?","What else comes to mind when you ask that?"],
              "WHERE" => ["Why do you ask?","Does that question interest you?","What answer would please you the most?","What do you think?","Are such questions on your mind often?","What is it that you really want to know?","Have you asked anyone else?","Have you asked such questions before?","What else comes to mind when you ask that?"],
              "WHEN" => ["Why do you ask?","Does that question interest you?","What answer would please you the most?","What do you think?","Are such questions on your mind often?","What is it that you really want to know?","Have you asked anyone else?","Have you asked such questions before?","What else comes to mind when you ask that?"],
              "WHY" => ["Why do you ask?","Does that question interest you?","What answer would please you the most?","What do you think?","Are such questions on your mind often?","What is it that you really want to know?","Have you asked anyone else?","Have you asked such questions before?","What else comes to mind when you ask that?"],
              "NAME" => ["Names don't interest me.", "I don't care about names, please go on."],
              "CAUSE" => ["Is that the real reason?","Don't any other reasons come to mind?","Does that reason explain anything else?","What other reasons might there be?"],
              "SORRY" => ["Please don't apologise!","Apologies are not necessary.","What feelings do you have when you apologise?","Don't be so defensive!"],
              "DREAM" => ["What does that dream suggest to you?","Do you dream often?","What persons appear in your dreams?","Are you disturbed by your dreams?"],
              "HELLO" => ["How are you today.. What would you like to discuss?"],
              "HI" => ["How are you today.. What would you like to discuss?"],
              "MAYBE" => ["You don't seem quite certain.","Why the uncertain tone?","Can't you be more positive?","You aren't sure?","Don't you know?"],
              "NO" => ["Are you saying no just to be negative?","You are being a bit negative.","Why not?","Are you sure?","Why no?"],
              "YOUR" => ["Why are you concerned about my <Q>","What about your own <Q>"],
              "ALWAYS" => ["Can you think of a specific example?","When?","What are you thinking of?","Really, always?"],
              "THINK" => ["Do you really think so?","But you are not sure you <Q>","Do you doubt you <Q>"],
              "ALIKE" => ["In what way?","What resemblence do you see?","What does the similarity suggest to you?","What other connections do you see?","Could there really be some connection?","How?","You seem quite positive."],
              "YES" => ["Are you Sure?","I see.","I understand."],
              "FRIEND" => ["Why do you bring up the topic of friends?","Do your friends worry you?","Do your friends pick on you?","Are you sure you have any friends?","Do you impose on your friends?","Perhaps your love for friends worries you."],
              "COMPUTER" => ["Do computers worry you?","Are you talking about me in particular?","Are you frightened by machines?","Why do you mention computers?","What do you think machines have to do with your problems?","Don't you think computers can help people?","What is it about machines that worries you?"],
              "NO KEY FOUND" => ["I didn't quite understand, can you say that another way?","What does that suggest to you?","I see.","I'm not sure I understand you fully.","That is quite interesting."]
            );

my %secondaryConjugationList = (
    "me am"  => "I am",
    "am me" => "am I",
    "me can"  => "I can",
    "can me" => "can I",
    "me have" => "I have",
    "me will" => "I will",
    "will me" => "will I"
);

 %primaryConjugationList = (
    "are" => "am",
    "am" => "are",
    "were" => "was",
    "was" => "were",
    "I" => "you",
    "me" => "you",
    "you" => "me",
    "my" => "your",
    "your" => "my",
    "mine" => "your's",
    "your's" => "mine",
    "I'm" => "you're",
    "you're" => "I'm",
    "I've" => "you've",
    "you've" => "I've",
    "I'll" => "you'll",
    "you'll" => "I'll",
    "myself" => "yourself",
    "yourself" => "myself"
);


$name = 

say "Hello I am Eliza, a trained psychotherapist. What is your name?";
$input = <STDIN>;
chomp($input);
if ($input =~ /([A-Z][a-z]+)/){
say "Hello $1. Lets get started. What's been bugging you lately?";
}

while(<STDIN>){
  last if ($_ =~ /^\s*$/); # Exit if it was just spaces (or just an enter)
  $string = $_;
  $string = stripString($string);
  print $string;
  $string = FindQuestion($string);
    $string = correctTense($string); 
  say $string;
}

sub stripString {
  $string = $_[0];
  $string =~ tr/a-zA-z //dc;

  return $string;
}

sub formQuestion {
  $string = $_[0];
  $response = $_[1];
  $keyword = $_[2];
  if($response =~ m/<Q>/){
      $modifier = findModifier($string,$keyword);
      
      $modifier = conjugate($modifier);
      $response =~ s/<Q>/$modifier/;
      $response = $response."?";
      return $response;
  }
  elsif($string =~ m/<S>/) {

      $modifier = findModifier($string,$keyword);
      $modifier = conjugate($modifier);
      $response =~ s/<S>/$modifier/;
      $response = $response.".";
      return $response;
  }
  else {
    return $response;
  }
}

sub findModifier {
  $string = $_[0];
  $phrase = $_[1];
  $string =~ /$phrase /i;
  return "$'";
}

sub FindQuestion {
  $string = $_[0];
  $max_responses = 5;
  foreach my $key (keys %keywordsWithResponses) {
    if ($string =~ m/\b$key\b/i)
    {
      my $number_of_questions = @{$keywordsWithResponses{$key}};
      my $random_response_index = int(rand($number_of_questions));
      $response = formQuestion($string,$keywordsWithResponses{$key}[$random_response_index],$key);
      return $response;
    }
  }
  return  $keywordsWithResponses{"NO KEY FOUND"}[int(rand($max_responses))];
}

sub conjugate {
  $string = $_[0];
  for my $word (keys %primaryConjugationList) {
     $string =~ s/\b$word\b/$primaryConjugationList{$word}/g;
    }   
    return $string;
}

sub correctTense {
  $string = $_[0];
  for my $phrase (keys %secondaryConjugationList) {
    $string =~ s/\b$phrase\b/$secondaryConjugationList{$phrase}/g;
  }
    return $string;
}

sub removeSpaces{
  $string = $_[0];
  $string =~ s/\s+//g;
  return $string;
}
